### ISSUE TITLE
MIME Type auf application/json stellen

### ISSUE THREAD

**Issue by mikeboy91** [tobibechtold/ReadmoreServer#1]
Hey ich benutze nen Browser Addon (JSONView für Firefox) für die (bessere) Darstellung von JSON. Um das aber darstellen zu können, muss der Server das auch als JSON "verkaufen". https://github.com/bhollis/jsonview in der README ganz unten bei Common Issues. Würde sich dann besser damit arbeiten lassen :)

**Comment by tobibechtold** [comment]
Hab ich mir mal vorgemerkt. Werde dass das nächste mal einbauen wenn ich die API verändere. So eine Änderung ist natürlich auch immer mit einem neuen deployen auf dem Server verbunden, daher kommt es erstmal ins Backlog.

**Comment by tobibechtold** [comment]
Hab den Application Type soeben auf JSON geändert. Bug sollte somit behoben sein.
